<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Parser\Expression\**" />
    <Compile Remove="Parser\Statement\**" />
    <EmbeddedResource Remove="Parser\Expression\**" />
    <EmbeddedResource Remove="Parser\Statement\**" />
    <None Remove="Parser\Expression\**" />
    <None Remove="Parser\Statement\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trs80.Level1Basic.Common\Trs80.Level1Basic.Common.csproj" />
    <ProjectReference Include="..\Trs80.Level1Basic.HostMachine\Trs80.Level1Basic.HostMachine.csproj" />
  </ItemGroup>

</Project>
