//
// This file is automatically generated. Do not modify.
//

using System;
using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Delete : Statement
{
    public int LineToDelete { get; }

    public Delete(int lineToDelete)
    {
        LineToDelete = lineToDelete;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitDeleteStatement(this);
    }
}
