//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System;
using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;
using Trs80.Level1Basic.Interpreter.Scanner;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Gosub : Statement
{
    public Expression Location { get; }

    public Gosub(Expression location)
    {
        Location = location;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitGosubStatement(this);
    }
}
