//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Goto : Statement
{
    public Expression Location { get; }

    public Goto(Expression location)
    {
        Location = location;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitGotoStatement(this);
    }
}
