//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class If : Statement
{
    public Expression Condition { get; }
    public Statement ThenStatement { get; }

    public If(Expression condition, Statement thenStatement)
    {
        Condition = condition;
        ThenStatement = thenStatement;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitIfStatement(this);
    }
}
