//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System;
using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;
using Trs80.Level1Basic.Interpreter.Scanner;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Input : Statement
{
    public List<Expression> Expressions { get; }
    public bool WriteNewline { get; }

    public Input(List<Expression> expressions, bool writeNewline)
    {
        Expressions = expressions;
        WriteNewline = writeNewline;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitInputStatement(this);
    }
}
