//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Let : Statement
{
    public Expression Variable { get; }
    public Expression Initializer { get; }

    public Let(Expression variable, Expression initializer)
    {
        Variable = variable;
        Initializer = initializer;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitLetStatement(this);
    }
}
