//
// This file is automatically generated. Do not modify.
//

using System;
using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Load : Statement
{
    public Expression Path { get; }

    public Load(Expression path)
    {
        Path = path;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitLoadStatement(this);
    }
}
