//
// This file is automatically generated. Do not modify.
//

using System;
using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Replace : Statement
{
    public ParsedLine Line { get; }

    public Replace(ParsedLine line)
    {
        Line = line;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitReplaceStatement(this);
    }
}
