//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Parser.Expressions;

namespace Trs80.Level1Basic.Interpreter.Parser.Statements;

public class Save : Statement
{
    public Expression Path { get; }

    public Save(Expression path)
    {
        Path = path;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitSaveStatement(this);
    }
}
