//
// This file is automatically generated. Do not modify.
//

using System;
using System.Collections.Generic;
using Trs80.Level1Basic.Services.Parser.Expressions;
using Trs80.Level1Basic.Domain;

namespace Trs80.Level1Basic.Services.Parser.Statements;

public class If : Statement
{
    public Expression Condition { get; }
    public Statement ThenStatement { get; }

    public If(Expression condition, Statement thenStatement)
    {
        Condition = condition;
        ThenStatement = thenStatement;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitIfStatement(this);
    }
}
