//
// This file is automatically generated. Do not modify.
//

using System;
using System.Collections.Generic;
using Trs80.Level1Basic.Services.Parser.Expressions;
using Trs80.Level1Basic.Domain;

namespace Trs80.Level1Basic.Services.Parser.Statements;

public class Merge : Statement
{
    public Expression Path { get; }

    public Merge(Expression path)
    {
        Path = path;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitMergeStatement(this);
    }
}
