//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//
//

using System.Collections.Generic;

using Trs80.Level1Basic.VirtualMachine.Exceptions;
using Trs80.Level1Basic.VirtualMachine.Scanner;
using Trs80.Level1Basic.VirtualMachine.Machine;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

public class Array : Expression
{
    public Token Name { get; init; }
    public Expression Index { get; init; }
    public Expression Index2 { get; init; }

    public Array(Token name, Expression index, int linePosition)
        : this(name, index, null, linePosition)
    {
    }

    public Array(Token name, Expression index, Expression index2, int linePosition) : base(linePosition)
    {
        Name = name;
        Index = index;
        Index2 = index2;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        CheckExceptions();
        return visitor.VisitArrayExpression(this);
    }
}
