//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//
//

using System.Collections.Generic;

using Trs80.Level1Basic.VirtualMachine.Exceptions;
using Trs80.Level1Basic.VirtualMachine.Scanner;
using Trs80.Level1Basic.VirtualMachine.Machine;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

public class Binary : Expression
{
    public Expression Left { get; init; }
    public Token BinaryOperator { get; init; }
    public Expression Right { get; init; }

    public Binary(Expression left, Token binaryOperator, Expression right, int linePosition) : base(linePosition)
    {
        Left = left;
        BinaryOperator = binaryOperator;
        Right = right;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        CheckExceptions();
        return visitor.VisitBinaryExpression(this);
    }
}
