//
//
// This file was automatically generated by generateAst
// at 2022-05-15 9:07:31 PM UTC. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Scanner;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

public class Binary : Expression
{
    public Expression Left { get; }
    public Token BinaryOperator { get; }
    public Expression Right { get; }

    public Binary(Expression left, Token binaryOperator, Expression right)
    {
        Left = left;
        BinaryOperator = binaryOperator;
        Right = right;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitBinaryExpression(this);
    }
}
