//
//
// This file was automatically generated by generateAst
// at 2022-06-11 11:04:28 PM UTC. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Scanner;
using Trs80.Level1Basic.VirtualMachine.Machine;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

public class Call : Expression
{
    public Token Name { get; init; }
    public Callable Callee { get; init; }
    public List<Expression> Arguments { get; init; }

    public Call(Token name, Callable callee, List<Expression> arguments)
    {
        Name = name;
        Callee = callee;
        Arguments = arguments;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitCallExpression(this);
    }
}
