//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//
//

using System.Collections.Generic;

using Trs80.Level1Basic.VirtualMachine.Exceptions;
using Trs80.Level1Basic.VirtualMachine.Scanner;
using Trs80.Level1Basic.VirtualMachine.Machine;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

public abstract class Expression
{
    public ParseException ParseException { get; set; }
    public int LinePosition { get; set; } = 0;

    protected Expression(int linePosition)
    {
        LinePosition = linePosition;
    }

    protected void CheckExceptions()
    {
        if (ParseException != null) throw ParseException;
    }

    public abstract T Accept<T>(IVisitor<T> visitor);
}
