//
//
// This file was automatically generated by generateAst
// at 2022-06-20 11:38:10 AM UTC. Do not modify.
//
//

namespace Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

public abstract class Expression
{
    public abstract T Accept<T>(IVisitor<T> visitor);
}
