//
//
// This file is automatically generated by generateAst. Do not modify.
//
//
namespace Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

public interface IExpressionVisitor
{
    dynamic VisitBasicArrayExpression(BasicArray expression);
    dynamic VisitAssignExpression(Assign expression);
    dynamic VisitBinaryExpression(Binary expression);
    dynamic VisitCallExpression(Call expression);
    dynamic VisitGroupingExpression(Grouping expression);
    dynamic VisitLiteralExpression(Literal expression);
    dynamic VisitUnaryExpression(Unary expression);
    dynamic VisitIdentifierExpression(Identifier expression);
}
