//
//
// This file was automatically generated by generateAst
// at 2022-05-19 6:42:09 PM UTC. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class Cls : Statement
{

    public Cls()
    {
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitClsStatement(this);
    }
}
