//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class End : Statement
{

    public End()
    {
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitEndStatement(this);
    }
}
