//
//
// This file was automatically generated by generateAst
// at 2022-05-15 2:13:58 AM UTC. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class For : Statement
{
    public Expression Variable { get; }
    public Expression StartValue { get; }
    public Expression EndValue { get; }
    public Expression StepValue { get; }

    public For(Expression variable, Expression startValue, Expression endValue, Expression stepValue)
    {
        Variable = variable;
        StartValue = startValue;
        EndValue = endValue;
        StepValue = stepValue;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitForStatement(this);
    }
}
