//
//
// This file was automatically generated by generateAst
// at 2022-06-21 2:33:37 AM UTC. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class For : Statement
{
    public Expression Identifier { get; init; }
    public Expression StartValue { get; init; }
    public Expression EndValue { get; init; }
    public Expression StepValue { get; init; }

    public For(Expression identifier, Expression startValue, Expression endValue, Expression stepValue)
    {
        Identifier = identifier;
        StartValue = startValue;
        EndValue = endValue;
        StepValue = stepValue;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitForStatement(this);
    }
}
