//
//
// This file is automatically generated by generateAst. Do not modify.
//
//
namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public interface IStatementVisitor
{
    void VisitClsStatement(Cls statement);
    void VisitContStatement(Cont statement);
    void VisitDataStatement(Data statement);
    void VisitDeleteStatement(Delete statement);
    void VisitEndStatement(End statement);
    void VisitForStatement(For statement);
    void VisitGotoStatement(Goto statement);
    void VisitGosubStatement(Gosub statement);
    void VisitIfStatement(If statement);
    void VisitInputStatement(Input statement);
    void VisitLetStatement(Let statement);
    void VisitListStatement(List statement);
    void VisitLoadStatement(Load statement);
    void VisitMergeStatement(Merge statement);
    void VisitNewStatement(New statement);
    void VisitNextStatement(Next statement);
    void VisitOnStatement(On statement);
    void VisitPrintStatement(Print statement);
    void VisitReplaceStatement(Replace statement);
    void VisitReadStatement(Read statement);
    void VisitRemStatement(Rem statement);
    void VisitRestoreStatement(Restore statement);
    void VisitReturnStatement(Return statement);
    void VisitRunStatement(Run statement);
    void VisitSaveStatement(Save statement);
    void VisitStatementExpressionStatement(StatementExpression statement);
    void VisitStopStatement(Stop statement);
}
