//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//
//
namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public interface IVisitor<out T>
{
    T VisitBeepStatement(Beep statement);
    T VisitClearStatement(Clear statement);
    T VisitClsStatement(Cls statement);
    T VisitCompoundStatement(Compound statement);
    T VisitContStatement(Cont statement);
    T VisitDataStatement(Data statement);
    T VisitDefTypeStatement(DefType statement);
    T VisitDefFunctionStatement(DefFunction statement);
    T VisitDimStatement(Dim statement);
    T VisitDeleteStatement(Delete statement);
    T VisitEndStatement(End statement);
    T VisitForStatement(For statement);
    T VisitGosubStatement(Gosub statement);
    T VisitGotoStatement(Goto statement);
    T VisitIfStatement(If statement);
    T VisitInputStatement(Input statement);
    T VisitLetStatement(Let statement);
    T VisitListStatement(List statement);
    T VisitLlistStatement(Llist statement);
    T VisitLprintStatement(Lprint statement);
    T VisitLoadStatement(Load statement);
    T VisitMergeStatement(Merge statement);
    T VisitMidAssignmentStatement(MidAssignment statement);
    T VisitNewStatement(New statement);
    T VisitNextStatement(Next statement);
    T VisitTronStatement(Tron statement);
    T VisitTroffStatement(Troff statement);
    T VisitOnStatement(On statement);
    T VisitOnErrorStatement(OnError statement);
    T VisitOutStatement(Out statement);
    T VisitPokeStatement(PokeStatement statement);
    T VisitPrintStatement(Print statement);
    T VisitReplaceStatement(Replace statement);
    T VisitReadStatement(Read statement);
    T VisitRemStatement(Rem statement);
    T VisitResetStatement(ResetStatement statement);
    T VisitRestoreStatement(Restore statement);
    T VisitReturnStatement(Return statement);
    T VisitResumeStatement(Resume statement);
    T VisitRunStatement(Run statement);
    T VisitSaveStatement(Save statement);
    T VisitSetStatement(SetStatement statement);
    T VisitStatementExpressionStatement(StatementExpression statement);
    T VisitStopStatement(Stop statement);
    T VisitSystemStatement(SystemStatement statement);
    T VisitWaitStatement(Wait statement);
}
