//
//
// This file was automatically generated by generateAst
// at 2022-05-19 6:42:09 PM UTC. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class List : Statement
{
    public Expression StartAtLineNumber { get; init; }

    public List(Expression startAtLineNumber)
    {
        StartAtLineNumber = startAtLineNumber;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitListStatement(this);
    }
}
