//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//

using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class Llist : Statement
{
    public Llist(Expression startAtLineNumber, Expression endAtLineNumber = null)
    {
        StartAtLineNumber = startAtLineNumber;
        EndAtLineNumber = endAtLineNumber;
    }

    public Expression StartAtLineNumber { get; }
    public Expression EndAtLineNumber { get; }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        CheckExceptions();
        return visitor.VisitLlistStatement(this);
    }
}
