//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//

using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class Out : Statement
{
    public Out(Expression port, Expression value)
    {
        Port = port;
        Value = value;
    }

    public Expression Port { get; }
    public Expression Value { get; }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        CheckExceptions();
        return visitor.VisitOutStatement(this);
    }
}
