//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class Rem : Statement
{
    public Literal Remark { get; }

    public Rem(Literal remark)
    {
        Remark = remark;
    }

    public override void Accept(IStatementVisitor visitor)
    {
        visitor.VisitRemStatement(this);
    }
}
