//
//
// This file was automatically generated by generateAst
// at 2022-06-13 12:03:06 AM UTC. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class Replace : Statement
{
    public IStatement Statement { get; init; }

    public Replace(IStatement statement)
    {
        Statement = statement;
    }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitReplaceStatement(this);
    }
}
