//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//

using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class SetStatement : Statement
{
    public SetStatement(Expression x, Expression y)
    {
        X = x;
        Y = y;
    }

    public Expression X { get; }
    public Expression Y { get; }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        CheckExceptions();
        return visitor.VisitSetStatement(this);
    }
}
