//
//
// This file was automatically generated by generateAst
// at 2022-06-21 2:33:37 AM UTC. Do not modify.
//
//

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public abstract class Statement: IStatement
{
    public int LineNumber { get; set; } = -1;
    public string SourceLine { get; set; }
    public IStatement Next { get; set; }
    public IStatement Previous { get; set; }
    public IStatement Enclosing { get; set; }

    public abstract T Accept<T>(IVisitor<T> visitor);
}
