//
//
// This file was automatically generated by generateAst
// at 2022-06-26 3:23:04 PM UTC. Do not modify.
//

using Trs80.Level1Basic.VirtualMachine.Parser.Expressions;

namespace Trs80.Level1Basic.VirtualMachine.Parser.Statements;

public class Wait : Statement
{
    public Wait(Expression port, Expression mask, Expression invert)
    {
        Port = port;
        Mask = mask;
        Invert = invert;
    }

    public Expression Port { get; }
    public Expression Mask { get; }
    public Expression Invert { get; }

    public override T Accept<T>(IVisitor<T> visitor)
    {
        CheckExceptions();
        return visitor.VisitWaitStatement(this);
    }
}
