//
// This file is automatically generated. Do not modify.
//

using System;
using System.Collections.Generic;

namespace Trs80.Level1Basic.Interpreter.Parser.Expressions;

public abstract class Expression
{
    public abstract dynamic Accept(IExpressionVisitor visitor);
}
