//
//
// This file is automatically generated by generateAst. Do not modify.
//
//

using System.Collections.Generic;
using Trs80.Level1Basic.Interpreter.Scanner;

namespace Trs80.Level1Basic.Interpreter.Parser.Expressions;

public class Literal : Expression
{
    public dynamic Value { get; }

    public Literal(dynamic value)
    {
        Value = value;
    }

    public override dynamic Accept(IExpressionVisitor visitor)
    {
        return visitor.VisitLiteralExpression(this);
    }
}
